{
  "tests/test_race.py::test_init_race_with_log_files": true,
  "tests/test_race.py::test_init_race_with_log_files_permission_error": true,
  "tests/test_race.py::test_init_race_with_log_files[FileNotFoundError-arg0]": true,
  "tests/test_race.py::test_init_race_with_log_files[PermissionError-arg1]": true,
  "tests/test_race.py::test_init_race_with_log_files[KeyError-arg2]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[FileNotFoundError-arg0]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[PermissionError-arg2]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[KeyError-arg3]": true,
  "tests/test_race.py::test_init_race_with_valid_log_files": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[PermissionError-arg3]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[KeyError-arg4]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[PermissionError-arg4]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[KeyError-arg5]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[FileNotFoundError-arg4]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[PermissionError-arg5]": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[KeyError-arg6]": true,
  "tests/test_race.py::test_invalid_file_path[PermissionError-arg1]": true,
  "tests/test_race.py::test_non_existent_file_path[PermissionError-arg0]": true,
  "tests/test_race.py::TestGetMethods::test_get_number_of_racers": true,
  "tests/test_race.py::TestGetMethods::test_dict_of_racers": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_names_of_racers[True-result0]": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_names_of_racers[False-result1]": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_racers_in_teams": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_racer_in_teams": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_racers_in_team[Ferrari-True]": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_racers_in_team[ferrari-True]": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_racers_in_team[FERRARI-False]": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_racers_in_team[FORCE INDIA MERCEDES-False]": true,
  "tests/test_report.py::TestCli::test_get_path_to_file_with_error": true,
  "tests/test_report.py::TestCli::test_output_no_argument": true,
  "tests/test_report.py::TestCli::test_output_with_no_argument": true,
  "tests/test_race.py::TestRaceGetMethods::test_get_data_of_race": true,
  "tests/test_report.py::TestCli::test_output_racers": true,
  "tests/test_report.py::TestCli::test_output_racers[True-result0]": true,
  "tests/test_report.py::TestCli::test_output_racers[False-result1]": true,
  "tests/test_report.py::TestCli::test_output_racers[desc-result0]": true,
  "tests/test_report.py::TestCli::test_output_racers[asc-result1]": true,
  "tests/test_report.py::TestCli::test_output_racers[asc-result0]": true,
  "tests/test_report.py::TestCli::test_output_racers[desc-result1]": true,
  "tests/test_race.py::test_non_existent_file_path": true,
  "tests/test_race.py::test_init_race_with_invalid_log_files[TypeError-arg3]": true,
  "tests/test_report.py::TestCli::test_output_racers_in_teams_error": true
}